import { useEffect, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { api } from "../../lib/api";
import { externalUrl, splitPreferences } from "../../lib/growth";
import { GrowthCard, GrowthFeedback, ResourceFeedback, growthButton, growthField, growthSecondary, useGrowthAction, useGrowthResource } from "./growth-ui";

type Job = { source?: string; source_id?: string; title: string; company: string; location: string; description: string; url: string; employment_type: string; alignment?: number | null; matched_skills?: string[]; missing_skills?: string[]; explanation?: string; salary_needs_review?: boolean };
type Preferences = { roles: string[]; locations: string[]; remote_only: boolean; minimum_salary: number | null; currency: string };
const emptyJob: Job = { title: "", company: "", location: "", description: "", url: "", employment_type: "" };

export function GrowthJobsPanel({ onSaved }: { onSaved: () => void }) {
  const jobs = useGrowthResource<{ configured: boolean; jobs: Job[]; errors: string[]; sources: string[] }>("/growth/jobs");
  const preferences = useGrowthResource<Preferences>("/growth/preferences");
  const capture = useGrowthAction();
  const matching = useGrowthAction();
  const [url, setUrl] = useState("");
  const [preview, setPreview] = useState<Job | null>(null);
  const [savedId, setSavedId] = useState<number | null>(null);
  const [roles, setRoles] = useState("");
  const [locations, setLocations] = useState("");
  const [remote, setRemote] = useState(false);
  const [salary, setSalary] = useState("");
  const [currency, setCurrency] = useState("INR");
  useEffect(() => { if (preferences.data) { const p = preferences.data; setRoles(p.roles.join(", ")); setLocations(p.locations.join(", ")); setRemote(p.remote_only); setSalary(p.minimum_salary == null ? "" : String(p.minimum_salary)); setCurrency(p.currency); } }, [preferences.data]);
  const fetchPreview = (event: FormEvent) => { event.preventDefault(); void capture.run(async () => { setSavedId(null); setPreview(null); const response = await api.post<Job>("/growth/jobs/preview", { url }); setPreview(response.data); }); };
  const save = (event: FormEvent) => { event.preventDefault(); void capture.run(async () => { if (!preview) return; const { title, company, location, description, employment_type, url } = preview; const response = await api.post<{ workspace_id: number; already_saved: boolean }>("/growth/jobs/save", { title, company, location, description, employment_type, url }); setSavedId(response.data.workspace_id); capture.setMessage(response.data.already_saved ? "This link is already in your target jobs." : "Job saved. Upload a resume in its workspace to start analysis."); setPreview(null); onSaved(); }); };
  const savePreferences = (event: FormEvent) => { event.preventDefault(); void matching.run(async () => { await api.put("/growth/preferences", { roles: splitPreferences(roles), locations: splitPreferences(locations), remote_only: remote, minimum_salary: salary === "" ? null : Number(salary), currency }); jobs.reload(); matching.setMessage("Matching preferences saved."); }); };
  return <div className="space-y-6"><GrowthCard title="Capture a job opportunity" description="Import a public Greenhouse or Lever listing using its official API. Review and edit the result before saving. Other job sites use manual capture; SkillSync does not scrape them.">
    <form onSubmit={fetchPreview} className="flex flex-col items-end gap-3 sm:flex-row"><label className="w-full text-sm">Job listing URL<input type="url" required className={growthField} value={url} onChange={e => setUrl(e.target.value)} placeholder="https://jobs.lever.co/company/job-id" /></label><button className={`${growthButton} shrink-0`} disabled={capture.busy}>Preview job</button></form>
    <button type="button" className={`${growthSecondary} mt-3`} disabled={capture.busy} onClick={() => { setPreview({ ...emptyJob, url }); setSavedId(null); }}>Enter description manually</button><GrowthFeedback {...capture} />
    {savedId && <Link className={`${growthSecondary} mt-3`} to={`/upload?workspace=${savedId}`}>Upload resume for saved job</Link>}
    {preview && <form onSubmit={save} className="mt-6 space-y-4"><p className="text-sm font-medium">Review before saving{preview.source ? ` · Source: ${preview.source}` : " · Manual capture"}</p><div className="grid gap-4 sm:grid-cols-2">{(["title", "company", "location", "employment_type", "url"] as const).map(key => <label key={key} className="text-sm">{{ title: "Job title", company: "Company", location: "Location", employment_type: "Employment type", url: "Source URL" }[key]}<input required={key === "title" || key === "url"} minLength={key === "title" ? 2 : undefined} maxLength={key === "url" ? 1000 : key === "employment_type" ? 80 : 160} type={key === "url" ? "url" : "text"} className={growthField} value={preview[key]} onChange={e => setPreview(p => p ? { ...p, [key]: e.target.value } : null)} /></label>)}</div><label className="block text-sm">Full job description<textarea required minLength={50} maxLength={50000} className={`${growthField} min-h-48`} value={preview.description} onChange={e => setPreview(p => p ? { ...p, description: e.target.value } : null)} /></label><p className="text-xs text-muted-foreground">Imported company names may be board identifiers. Confirm the employer, salary, work authorization, and listing freshness yourself.</p><div className="flex gap-3"><button className={growthButton} disabled={capture.busy}>Save reviewed job</button><button type="button" className={growthSecondary} onClick={() => setPreview(null)}>Cancel</button></div></form>}
  </GrowthCard><GrowthCard title="Discover relevant opportunities" description="Match configured employer feeds to your preferences and latest passed knowledge checks. Skill alignment is explainable, but is not an ATS score or an eligibility guarantee.">
    <ResourceFeedback resource={preferences} />
    {preferences.data && <form onSubmit={savePreferences} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Role keywords, separated by commas<input className={growthField} value={roles} maxLength={1000} onChange={e => setRoles(e.target.value)} placeholder="Frontend, Python, Graduate" /></label><label className="text-sm">Locations, separated by commas<input className={growthField} value={locations} maxLength={1000} onChange={e => setLocations(e.target.value)} placeholder="Bengaluru, Pune" /></label><label className="text-sm">Minimum annual salary (optional)<input type="number" min={0} max={100000000} className={growthField} value={salary} onChange={e => setSalary(e.target.value)} /></label><label className="text-sm">Salary currency<select className={growthField} value={currency} onChange={e => setCurrency(e.target.value)}>{["INR", "USD", "EUR", "GBP", "CAD", "AUD"].map(c => <option key={c}>{c}</option>)}</select></label></div><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={remote} onChange={e => setRemote(e.target.checked)} />Remote listings only</label><button className={growthButton} disabled={matching.busy}>Update matches</button><GrowthFeedback {...matching} /></form>}
    <ResourceFeedback resource={jobs} />
    {jobs.data && !jobs.data.configured && <p className="mt-5 rounded-xl border border-dashed border-border p-5 text-sm text-muted-foreground">Live feeds are not configured yet. An administrator must add permitted Greenhouse board names or Lever company names. Job-link import and manual capture work independently.</p>}
    {jobs.data?.errors.map(error => <p key={error} role="status" className="mt-3 text-sm text-muted-foreground">{error}</p>)}
    {jobs.data?.configured && !jobs.loading && !jobs.data.jobs.length && <p className="mt-5 text-sm text-muted-foreground">No matching opportunities in the available feeds. Broaden your preferences or try again later.</p>}
    <div className="mt-6 grid gap-4 md:grid-cols-2">{jobs.data?.jobs.map(job => <article key={job.source_id} className="min-w-0 rounded-xl border border-border p-5"><h3 className="font-medium">{job.title}</h3><p className="mt-2 text-sm text-muted-foreground">{job.company} · {job.location || "Location not supplied"}</p><p className="mt-3 text-sm">{job.alignment == null ? "Skill alignment unavailable" : `${job.alignment}% recognized-skill alignment`}</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{job.explanation}</p><p className="mt-3 text-sm">Checks passed: {job.matched_skills?.join(", ") || "None"}</p><p className="mt-2 text-sm">Skills to assess or practise: {job.missing_skills?.join(", ") || "None recognized"}</p>{job.salary_needs_review && <p className="mt-2 text-xs text-muted-foreground">Salary information needs manual review.</p>}<div className="mt-4 flex flex-wrap gap-3">{externalUrl(job.url) && <a className={growthSecondary} href={externalUrl(job.url)} target="_blank" rel="noopener noreferrer">Original listing</a>}<button type="button" className={growthSecondary} onClick={() => { setPreview(job); setUrl(job.url); setSavedId(null); window.scrollTo({ top: 0, behavior: "instant" }); }}>Review and save</button></div></article>)}</div>
  </GrowthCard></div>;
}
