import { useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { api } from "../../lib/api";
import { downloadBlob, externalUrl, localDate } from "../../lib/growth";
import { GrowthCard, GrowthFeedback, ResourceFeedback, growthButton, growthField, growthSecondary, useGrowthAction, useGrowthResource } from "./growth-ui";
import type { GrowthWorkspace } from "./growth-planner-panel";

type Contact = { id?: number; workspace_id?: number; name: string; contact_type: string; email: string | null; url: string | null; notes: string; communication_history: string };
export type Reminder = { id: string; title: string; due_date: string; path: string; workspace_id: number | null; kind: string };
const emptyContact: Contact = { name: "", contact_type: "recruiter", email: "", url: "", notes: "", communication_history: "" };

export function GrowthContactsPanel({ workspace }: { workspace?: GrowthWorkspace }) {
  const contacts = useGrowthResource<Contact[]>("/growth/contacts");
  const reminders = useGrowthResource<{ items: Reminder[]; today: string; delivery: string }>("/growth/reminders");
  const contactAction = useGrowthAction();
  const reminderAction = useGrowthAction();
  const [draft, setDraft] = useState<Contact>(emptyContact);
  const [title, setTitle] = useState("");
  const [dueDate, setDueDate] = useState(localDate());
  const saveContact = (event: FormEvent) => { event.preventDefault(); void contactAction.run(async () => {
    const payload = { workspace_id: workspace?.id, name: draft.name, contact_type: draft.contact_type,
      email: draft.email || null, url: draft.url || null, notes: draft.notes, communication_history: draft.communication_history };
    if (draft.id) await api.put(`/growth/contacts/${draft.id}`, payload); else await api.post("/growth/contacts", payload);
    setDraft(emptyContact); contacts.reload(); contactAction.setMessage("Contact saved. No message has been sent.");
  }); };
  const saveReminder = (event: FormEvent) => { event.preventDefault(); void reminderAction.run(async () => {
    await api.post("/growth/reminders", { title, due_date: dueDate, workspace_id: workspace?.id || null });
    setTitle(""); reminders.reload(); reminderAction.setMessage("Reminder saved to your in-app inbox. Export it to your calendar for alerts outside SkillSync.");
  }); };
  const dismiss = (id: string) => reminderAction.run(async () => { await api.post(`/growth/reminders/${encodeURIComponent(id)}/dismiss`); reminders.reload(); reminderAction.setMessage("Reminder dismissed. Learning progress and application status were not changed."); });
  const calendar = () => reminderAction.run(async () => { const response = await api.get("/growth/calendar", { responseType: "blob" }); downloadBlob(response.data, "skillsync-calendar.ics"); });
  return <div className="grid gap-6 xl:grid-cols-2"><div className="space-y-6"><GrowthCard title="People connected to this opportunity" description="Keep recruiters, hiring managers, referrals, and communication notes together. Contact details stay private; SkillSync never sends messages automatically.">
    {workspace ? <form onSubmit={saveContact} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Contact name<input required minLength={2} maxLength={160} className={growthField} value={draft.name} onChange={e => setDraft(d => ({ ...d, name: e.target.value }))} /></label><label className="text-sm">Relationship<select className={growthField} value={draft.contact_type} onChange={e => setDraft(d => ({ ...d, contact_type: e.target.value }))}>{["recruiter", "hiring_manager", "referral", "mentor", "other"].map(t => <option key={t} value={t}>{t.replace("_", " ")}</option>)}</select></label><label className="text-sm">Email (optional)<input type="email" maxLength={320} className={growthField} value={draft.email || ""} onChange={e => setDraft(d => ({ ...d, email: e.target.value }))} /></label><label className="text-sm">Profile URL (optional)<input type="url" className={growthField} value={draft.url || ""} onChange={e => setDraft(d => ({ ...d, url: e.target.value }))} /></label></div><label className="block text-sm">Private notes<textarea maxLength={4000} className={`${growthField} min-h-24`} value={draft.notes} onChange={e => setDraft(d => ({ ...d, notes: e.target.value }))} /></label><label className="block text-sm">Communication history<textarea maxLength={6000} className={`${growthField} min-h-24`} value={draft.communication_history} onChange={e => setDraft(d => ({ ...d, communication_history: e.target.value }))} placeholder="Date, channel, what you discussed, and agreed next steps" /></label><div className="flex gap-3"><button className={growthButton} disabled={contactAction.busy}>{draft.id ? "Save contact changes" : "Add contact"}</button>{draft.id && <button type="button" className={growthSecondary} onClick={() => setDraft(emptyContact)}>Cancel edit</button>}</div></form> : <p className="text-sm text-muted-foreground">Create or select a target job to connect a contact.</p>}
    <GrowthFeedback {...contactAction} /><ResourceFeedback resource={contacts} />
    <div className="mt-5 space-y-3">{contacts.data?.filter(contact => contact.workspace_id === workspace?.id).map(contact => <article key={contact.id} className="rounded-xl border border-border p-4"><h3 className="font-medium">{contact.name}</h3><p className="mt-1 text-sm text-muted-foreground">{contact.contact_type.replace("_", " ")}{contact.email ? ` · ${contact.email}` : ""}</p>{contact.notes && <p className="mt-3 whitespace-pre-wrap text-sm">{contact.notes}</p>}{contact.communication_history && <p className="mt-3 whitespace-pre-wrap text-sm text-muted-foreground">{contact.communication_history}</p>}<div className="mt-4 flex flex-wrap gap-2">{externalUrl(contact.url) && <a href={externalUrl(contact.url)} className={growthSecondary} target="_blank" rel="noopener noreferrer">Profile</a>}<button type="button" className={growthSecondary} onClick={() => setDraft(contact)}>Edit</button><button type="button" className={`${growthSecondary} text-destructive`} disabled={contactAction.busy} onClick={() => { if (window.confirm(`Delete ${contact.name} from your contacts? This cannot be undone.`)) void contactAction.run(async () => { await api.delete(`/growth/contacts/${contact.id}`); contacts.reload(); if (draft.id === contact.id) setDraft(emptyContact); contactAction.setMessage("Contact removed. It cannot be recovered through the app."); }); }}>Delete</button></div></article>)}</div>
  </GrowthCard></div><div className="space-y-6"><GrowthCard title="Follow-up and learning inbox" description="Application next-action dates and unfinished learning deadlines appear automatically. Add personal follow-ups below. Delivery is in-app and through calendar export—not email or push notifications.">
    <form onSubmit={saveReminder} className="space-y-4"><label className="block text-sm">Reminder<input required minLength={2} maxLength={300} className={growthField} value={title} onChange={e => setTitle(e.target.value)} placeholder="Ask your referral for an introduction" /></label><label className="block text-sm">Due date<input required type="date" className={growthField} value={dueDate} onChange={e => setDueDate(e.target.value)} /></label><div className="flex flex-wrap gap-3"><button className={growthButton} disabled={reminderAction.busy}>Add reminder</button><button type="button" className={growthSecondary} disabled={reminderAction.busy} onClick={calendar}>Export calendar</button></div></form><GrowthFeedback {...reminderAction} /><ResourceFeedback resource={reminders} />
    <div className="mt-5 space-y-3">{reminders.data?.items.map(reminder => <article key={reminder.id} className="rounded-xl border border-border p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><h3 className="font-medium">{reminder.title}</h3><p className="mt-2 text-sm text-muted-foreground">{reminder.due_date} · {reminder.kind} · {reminder.due_date < (reminders.data?.today || localDate()) ? "Overdue" : reminder.due_date === reminders.data?.today ? "Due today" : "Upcoming"}</p></div><button type="button" className={`${growthSecondary} shrink-0 self-start`} disabled={reminderAction.busy} onClick={() => dismiss(reminder.id)}>Dismiss reminder</button></div><Link to={reminder.path} className={`${growthSecondary} mt-3`}>Open related workspace</Link></article>)}{reminders.data && !reminders.data.items.length && <p className="text-sm text-muted-foreground">You are caught up. New deadlines and follow-ups will appear here.</p>}</div>
  </GrowthCard></div></div>;
}
