import { useState, type FormEvent } from "react";
import { api } from "../../lib/api";
import { GrowthCard, GrowthFeedback, ResourceFeedback, growthButton, growthField, growthSecondary, useGrowthAction, useGrowthResource } from "./growth-ui";
import type { SkillAttempt } from "./skill-assessments-panel";

type Evidence = { id: number; title: string; description: string; skills: string[]; url: string | null; verification_status: string };
type Share = { id: number; expires_at: string; revoked: boolean; created_at: string; snapshot: { evidence: Evidence[]; assessments: { skill: string; score: number }[] } };

export function GrowthPassportPanel() {
  const options = useGrowthResource<{ evidence: Evidence[]; assessments: SkillAttempt[] }>("/growth/passport/options");
  const shares = useGrowthResource<Share[]>("/growth/passport/shares");
  const action = useGrowthAction();
  const [evidenceIds, setEvidenceIds] = useState<number[]>([]);
  const [assessmentIds, setAssessmentIds] = useState<number[]>([]);
  const [days, setDays] = useState(7);
  const [consent, setConsent] = useState(false);
  const [link, setLink] = useState("");
  const toggle = (ids: number[], id: number) => ids.includes(id) ? ids.filter(value => value !== id) : [...ids, id];
  const create = (event: FormEvent) => { event.preventDefault(); void action.run(async () => {
    const response = await api.post<{ path: string }>("/growth/passport/shares", { evidence_ids: evidenceIds, assessment_ids: assessmentIds, expires_in_days: days, sharing_consent: consent });
    setLink(`${window.location.origin}${response.data.path}`); shares.reload(); action.setMessage("Passport link created. Copy it now; the secret link is not stored in recoverable form. You can revoke it below.");
  }); };
  return <div className="space-y-6"><GrowthCard title="Publish a selected Skills Passport" description="Choose exactly what to share. The published snapshot includes your Career Vault name and headline, selected project descriptions/links, and selected assessment scores—not your email, phone, private contact notes, raw resume, or interview answers.">
    <ResourceFeedback resource={options} />
    {options.data && <form onSubmit={create} className="space-y-5"><fieldset><legend className="text-sm font-medium">Project evidence · self-reported</legend><div className="mt-3 space-y-2">{options.data.evidence.map(evidence => <label key={evidence.id} className="flex min-h-11 cursor-pointer items-start gap-3 rounded-xl border border-border p-4"><input className="mt-1" type="checkbox" checked={evidenceIds.includes(evidence.id)} onChange={() => setEvidenceIds(ids => toggle(ids, evidence.id))} /><span><span className="block text-sm font-medium">{evidence.title}</span><span className="mt-1 block text-xs text-muted-foreground">{evidence.skills.join(", ")} · Self-reported; not automatically verified</span><span className="mt-2 block text-sm text-muted-foreground">{evidence.description}</span></span></label>)}{!options.data.evidence.length && <p className="text-sm text-muted-foreground">Add project evidence in Career Hub before sharing it.</p>}</div></fieldset><fieldset><legend className="text-sm font-medium">Knowledge checks · unproctored</legend><div className="mt-3 space-y-2">{options.data.assessments.map(attempt => <label key={attempt.id} className="flex min-h-11 cursor-pointer items-center gap-3 rounded-xl border border-border p-4 text-sm"><input type="checkbox" checked={assessmentIds.includes(attempt.id)} onChange={() => setAssessmentIds(ids => toggle(ids, attempt.id))} /><span>{attempt.skill} · {attempt.score}% · {new Date(attempt.submitted_at || attempt.created_at).toLocaleDateString()} · Knowledge assessed</span></label>)}{!options.data.assessments.length && <p className="text-sm text-muted-foreground">Complete a knowledge check to include its result.</p>}</div></fieldset><label className="block max-w-xs text-sm">Link expires after<select className={growthField} value={days} onChange={e => setDays(Number(e.target.value))}>{[1, 7, 14, 30].map(day => <option key={day} value={day}>{day} {day === 1 ? "day" : "days"}</option>)}</select></label><label className="flex min-h-11 items-start gap-3 text-sm leading-relaxed"><input className="mt-1" required type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} /><span>I agree to share this selected snapshot with anyone who has the link. They may copy it. Revocation stops future access but cannot recall downloaded copies.</span></label><button className={growthButton} disabled={action.busy || !consent || !evidenceIds.length && !assessmentIds.length}>Create sharing link</button></form>}
    <GrowthFeedback {...action} />
    {link && <div className="mt-5 rounded-xl border border-border bg-muted p-4"><label className="block text-sm">Your sharing link<input readOnly className={growthField} value={link} onFocus={e => e.target.select()} /></label><div className="mt-3 flex flex-wrap gap-3"><a href={link} target="_blank" rel="noopener noreferrer" className={growthSecondary}>Preview passport</a><button type="button" className={growthSecondary} onClick={() => void action.run(async () => { await navigator.clipboard.writeText(link); action.setMessage("Link copied. Share it only with people you choose."); })}>Copy link</button></div><p className="mt-3 text-xs text-muted-foreground">If copying is unavailable, select the link above and copy it manually.</p></div>}
  </GrowthCard><GrowthCard title="Manage shared snapshots" description="Links expire automatically. Revoking a link also makes its public reviews inaccessible. Reviews are linked to signed-in accounts, but reviewer identity and expertise are not independently verified.">
    <ResourceFeedback resource={shares} /><div className="space-y-3">{shares.data?.map(share => <article key={share.id} className="flex flex-col justify-between gap-4 rounded-xl border border-border p-4 sm:flex-row"><div><p className="font-medium">Passport #{share.id} · {share.revoked ? "Revoked" : new Date(share.expires_at) <= new Date() ? "Expired" : "Active"}</p><p className="mt-2 text-sm text-muted-foreground">{share.snapshot.evidence.length} projects · {share.snapshot.assessments.length} checks · Expires {new Date(share.expires_at).toLocaleDateString()}</p></div><button type="button" className={`${growthSecondary} shrink-0 self-start text-destructive`} disabled={action.busy || share.revoked} onClick={() => { if (window.confirm("Revoke this passport link? Anyone using it will lose access.")) void action.run(async () => { await api.delete(`/growth/passport/shares/${share.id}`); setLink(""); shares.reload(); action.setMessage("Sharing link revoked. Previously copied information cannot be recalled."); }); }}>Revoke link</button></article>)}{shares.data && !shares.data.length && <p className="text-sm text-muted-foreground">No sharing links yet. Your evidence remains private until you create one.</p>}</div>
  </GrowthCard></div>;
}
